Repository P4-Games/ChatterPay-SmartContracts, pull requests merged in 2025-05, with the labels that each got.

#149 merge Fix/scroll-swap-error into develop
  script/uniswap_check_liquidity.sh
  script/utils/HelperConfig.s.sol
  src/ChatterPay.sol
Labels: bug

#150 merge feature/adjust-uniswap-script into develop
  script/uniswap_check_liquidity.sh
  script/utils/HelperConfig.s.sol
Labels: enhancement

#152 merge feature/eip-712 into develop
  src/ChatterPay.sol
Labels: enhancement

#156 merge feat/scr-mainnet-addresses into develop
  script/utils/HelperConfig.s.sol
Labels: enhancement

#159 merge feature/157-default-fee into develop
  script/utils/HelperConfig.s.sol
  src/ChatterPay.sol
Labels: enhancement

#160 merge feature/doc-uniswap into develop
  .doc/deployment/deployment-guidelines.md
Labels: documentation

#161 merge fix/test-default-fee in develop
  test/modules/AdminModule.t.sol
  test/modules/SwapModule.t.sol
  test/modules/TransferModule.t.sol
Labels: bug
